blueprint:
  name: Turn off A/C when empty (optional v5)
  description: |
    Turns off the A/C when the apartment has been empty for a configurable
    period. Power-, on/off-sensor, failure counter, Google Sheet logging and
    automation-running flag are **optional**; if you leave them blank their
    features are skipped.

    **v5** — La acción que apaga el aire se ejecuta SIEMPRE primero; el resto
    (registro, contadores, flag, reintento) solo se dispara si el sensor indica
    que el aire estaba encendido.
  domain: automation

  input:
    apartment_id:
      name: Apartment ID
      selector:
        text:
      default: "1-1"

    presence_sensor:
      name: Presence Sensor
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: occupancy
            - domain: binary_sensor
              device_class: presence
          multiple: false

    empty_duration:
      name: Empty Duration
      selector:
        duration:
      default: "00:45:00"

    not_empty_duration:
      name: Not-empty Duration
      selector:
        duration:
      default: "00:05:30"

    ac_power_sensor:
      name: A/C Power Sensor (optional)
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: power
          multiple: false
      default: ""

    ac_sensor_on_off:
      name: A/C Sensor (optional)
      description: Binary sensor with *device_class* **running** or **power**.
      selector:
        entity:
          filter:
            - domain: binary_sensor
              device_class: running
            - domain: binary_sensor
              device_class: power
          multiple: false
      default: ""

    ac_success_counter:
      name: A/C Success Counter
      selector:
        entity:
          filter:
            - domain: counter
          multiple: false

    ac_failure_counter:
      name: A/C Failure Counter (optional)
      selector:
        entity:
          filter:
            - domain: counter
          multiple: false
      default: ""

    google_sheet:
      name: Google Sheet (optional)
      selector:
        config_entry:
          integration: google_sheets
      default: ""

    google_sheet_name:
      name: Worksheet name
      selector:
        text:
      default: "log"

    is_automation_running:
      name: Is Automation Running (optional)
      selector:
        entity:
          filter:
            - domain: input_boolean
          multiple: false
      default: ""

    turn_off_ac_action:
      name: Turn-off A/C action
      selector:
        action:

    turn_off_retry_delay:
      name: Retry delay
      selector:
        duration:
      default: "00:05:00"

variables:
  ac_power_sensor_id: !input ac_power_sensor
  ac_sensor_on_off_id: !input ac_sensor_on_off
  ac_failure_counter_id: !input ac_failure_counter
  google_sheet_id: !input google_sheet
  is_automation_running_id: !input is_automation_running

trigger:
  - platform: state
    id: empty
    entity_id: !input presence_sensor
    to: "off"
    for: !input empty_duration
  - platform: state
    id: not_empty
    entity_id: !input presence_sensor
    to: "on"
    for: !input not_empty_duration

action:
  - choose:
      # ------------------------  EMPTY  ------------------------ #
      - conditions:
          - condition: trigger
            id: empty
        sequence:
          # 1️⃣ Apagar el aire SIEMPRE
          - sequence: !input turn_off_ac_action

          # 2️⃣ Evaluar si el sensor dice que estaba encendido
          - variables:
              ac_running: >-
                {{ (ac_sensor_on_off_id != '') and is_state(ac_sensor_on_off_id,'on') }}

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ ac_running }}"
                sequence:
                  # --- Log en Google Sheet ---
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ google_sheet_id != '' }}"
                        sequence:
                          - service: google_sheets.append_sheet
                            data:
                              config_entry: !input google_sheet
                              worksheet: !input google_sheet_name
                              data:
                                type: "OFF"
                                consumption: >-
                                  {{ (states(ac_power_sensor_id)|float(0)) if ac_power_sensor_id != '' else 0 }}
                                apartment: !input apartment_id

                  # --- Éxito ---
                  - service: counter.increment
                    data:
                      entity_id: !input ac_success_counter

                  # --- Flag opcional ---
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ is_automation_running_id != '' }}"
                        sequence:
                          - service: homeassistant.turn_on
                            data:
                              entity_id: "{{ is_automation_running_id }}"

          # 3️⃣ Reintento si tenemos sensor on/off
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ ac_sensor_on_off_id != '' }}"
                sequence:
                  - delay: !input turn_off_retry_delay
                  - condition: state
                    entity_id: !input ac_sensor_on_off
                    state: "on"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ ac_failure_counter_id != '' }}"
                        sequence:
                          - service: counter.increment
                            data:
                              entity_id: "{{ ac_failure_counter_id }}"
                  - sequence: !input turn_off_ac_action

      # ------------------------  NOT EMPTY  -------------------- #
      - conditions:
          - condition: trigger
            id: not_empty
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_automation_running_id != '' }}"
                sequence:
                  - service: homeassistant.turn_off
                    data:
                      entity_id: "{{ is_automation_running_id }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ google_sheet_id != '' }}"
                sequence:
                  - service: google_sheets.append_sheet
                    data:
                      config_entry: !input google_sheet
                      worksheet: !input google_sheet_name
                      data:
                        type: "VUELTA"
                        apartment: !input apartment_id

mode: restart
